loaders:
  - type: python
    search_path: ["."]
    modules: [daytona_sdk.daytona]

processors:
  - type: filter
  - type: smart
  - type: crossref

renderer:
  type: markdown
  render_toc: true
  descriptive_class_title: true
  descriptive_module_title: true
  source_linker:
    type: github
    repo: daytonaio/daytona-client 