loaders:
  - type: python
    search_path: ["src"]
    modules:
      - daytona_sdk.daytona
      - daytona_sdk.workspace
      - daytona_sdk.filesystem
      - daytona_sdk.git
      - daytona_sdk.process
      - daytona_sdk.lsp_server

processors:
  - type: filter
  - type: smart
  - type: crossref

renderer:
  type: markdown
  render_toc: true
  descriptive_class_title: true
  descriptive_module_title: true
  source_linker:
    type: github
    repo: daytonaio/daytona-client