name: Publish to TestPyPI

on:
  pull_request:
    types: [opened, synchronize] # Trigger on new PRs and new commits in a PR

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for Trusted Publisher authentication

    defaults:
      run:
        working-directory: packages/python # Set the working directory for all run steps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade setuptools wheel twine tomli tomli-w build

      - name: Extract Version and Bump to Pre-Release
        run: |
          MAIN_VERSION=$(python3 -c "import tomli; from pathlib import Path; \
            content = Path('pyproject.toml').read_text(); \
            print(tomli.loads(content)['project']['version'])")

          NEW_VERSION="${MAIN_VERSION}rc${{ github.run_number }}"

          echo "Extracted main version: $MAIN_VERSION"
          echo "Bumping version to: $NEW_VERSION"

          # Update the version in pyproject.toml
          python3 -c "
          import tomli, tomli_w
          from pathlib import Path

          toml_path = Path('pyproject.toml')
          data = tomli.loads(toml_path.read_text())
          data['project']['version'] = '$NEW_VERSION'
          toml_path.write_text(tomli_w.dumps(data))
          "

      - name: Build the package
        run: |
          rm -rf dist/*
          python3 -m build

      - name: Publish to TestPyPI using Trusted Publisher
        run: |
          twine upload --repository testpypi dist/* --verbose
