name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with 'v'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for Trusted Publisher authentication

    defaults:
      run:
        working-directory: packages/python  # Set working directory

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Tag Format
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "Tag name: $TAG_NAME"

          # Validate tag format: vX.Y.Z, vX.Y, vX.Y.ZaN, vX.Y.ZbN, vX.Y.ZrcN
          if [[ ! "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+(\.[0-9]+)?(a[0-9]+|b[0-9]+|rc[0-9]+)?$ ]]; then
            echo "Invalid tag format: $TAG_NAME"
            echo "Allowed formats: vX.Y, vX.Y.Z, vX.Y.ZaN, vX.Y.ZbN, vX.Y.ZrcN"
            exit 1
          fi

          # Extract version from tag (remove 'v' prefix)
          echo "PACKAGE_VERSION=${TAG_NAME#v}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          pip install --upgrade build twine

      - name: Build the package with version argument
        run: |
          python3 -m build --config-setting "--version=${PACKAGE_VERSION}"

      - name: Publish to PyPI using Trusted Publisher
        run: |
          twine upload --repository testpypi dist/* --verbose # TODO: publish-pipeline; change to pypi

      - name: Display Published Package Info
        run: |
          PACKAGE_NAME=$(python3 -c "import tomli; from pathlib import Path; \
            content = Path('pyproject.toml').read_text(); \
            print(tomli.loads(content)['project']['name'])")

          echo "Successfully published $PACKAGE_NAME==$PACKAGE_VERSION to PyPI!"
          echo "Install it using:"
          echo -e "\tpip install $PACKAGE_NAME==$PACKAGE_VERSION"
